backend:
  name: git-gateway
  branch: master
media_folder: "public/sections"
public_folder: "/sections"
collections:
  - name: "en"
    label: "English Sections"
    folder: "public/sections/en"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "es"
    label: "Secciones Español"
    folder: "public/sections/es"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "English Stages Section"
    name: "en stages"
    files:
      - label: "Stage 1 Inside"
        name: "section-1-inside"
        file: "public/admin/sections/en/stages/stage-1/inside.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Stage 1 Outside"
        name: "section-1-outside"
        file: "public/admin/sections/en/stages/stage-1/outside.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
