backend:
  name: git-gateway
  branch: master
media_folder: "src/assets/img/"
public_folder: "./public"
publish_mode: editorial_workflow
collections:
  - label: "English Sections"
    name: "en"
    folder: "public/sections/en"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "English Stages"
    name: "en-stages"
    files:
      - label: "Stage 1 Inside"
        name: "section-1-inside"
        file: "public/sections/en/stages/stage-1/inside.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Stage 1 Outside"
        name: "section-1-outside"
        file: "public/sections/en/stages/stage-1/outside.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Stage 2 Inside"
        name: "section-2-inside"
        file: "public/sections/en/stages/stage-2/inside.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Stage 2 Outside"
        name: "section-2-outside"
        file: "public/sections/en/stages/stage-2/outside.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Stage 3 Inside"
        name: "section-3-inside"
        file: "public/sections/en/stages/stage-3/inside.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Stage 3 Outside"
        name: "section-3-outside"
        file: "public/sections/en/stages/stage-3/outside.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Stage 4 Inside"
        name: "section-4-inside"
        file: "public/sections/en/stages/stage-4/inside.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Stage 4 Outside"
        name: "section-4-outside"
        file: "public/sections/en/stages/stage-4/outside.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
  - label: "English Steps"
    name: "en-steps"
    files:
      - label: "Title"
        name: "step-title"
        file: "public/sections/en/steps/title.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Step 1"
        name: "step-1"
        file: "public/sections/en/steps/step-1.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Step 2"
        name: "step-2"
        file: "public/sections/en/steps/step-2.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Step 3"
        name: "step-3"
        file: "public/sections/en/steps/step-3.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
  - label: "Secciones Español"
    name: "es"
    folder: "public/sections/es"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Etapas Español"
    name: "es-stages"
    files:
      - label: "Etapa 1 Inside"
        name: "section-1-inside"
        file: "public/sections/es/stages/stage-1/inside.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Etapa 1 Outside"
        name: "section-1-outside"
        file: "public/sections/es/stages/stage-1/outside.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Etapa 2 Inside"
        name: "section-2-inside"
        file: "public/sections/es/stages/stage-2/inside.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Etapa 2 Outside"
        name: "section-2-outside"
        file: "public/sections/es/stages/stage-2/outside.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Etapa 3 Inside"
        name: "section-3-inside"
        file: "public/sections/es/stages/stage-3/inside.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Etapa 3 Outside"
        name: "section-3-outside"
        file: "public/sections/es/stages/stage-3/outside.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Etapa 4 Inside"
        name: "section-4-inside"
        file: "public/sections/es/stages/stage-4/inside.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Etapa 4 Outside"
        name: "section-4-outside"
        file: "public/sections/es/stages/stage-4/outside.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
  - label: "Pasos Español"
    name: "es-steps"
    files:
      - label: "Titulo"
        name: "step-title"
        file: "public/sections/es/steps/title.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Paso 1"
        name: "step-1"
        file: "public/sections/es/steps/step-1.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Paso 2"
        name: "step-2"
        file: "public/sections/es/steps/step-2.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Paso 3"
        name: "step-3"
        file: "public/sections/es/steps/step-3.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
