backend:
  name: git-gateway
  branch: master
media_folder: "public/sections"
public_folder: "/src/assets/img"
collections:
  - name: "en"
    label: "English Sections"
    folder: "public/sections/en"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "es"
    label: "Secciones Español"
    folder: "public/sections/es"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
