backend:
  name: git-gateway
  branch: master
media_folder: "public/sections"
public_folder: "/sections"
collections:
  - name: "Test En"
    label: "test"
    folder: "public/sections/en"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Body", name: "body", widget: "markdown" }
